usb: ehci-imx6: fix compilation errors
Fixed the following errors:
  drivers/usb/host/ehci-mx6.c: In function ‘ehci_hcd_init’:
  drivers/usb/host/ehci-mx6.c:144:32: error: ‘phy_bases’ undeclared (first use in this function)
  144 |         if (index < ARRAY_SIZE(phy_bases))

Note:
  - The same error is reproducible building U-Boot with the NXP target mx6sabreauto_defconfig
  - Also, building U-Boot with the NXP target mx6sabresd_defconfig fails

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>
(cherry picked from commit cc7821cc3ed5a15b23360a4e04a83e898486eb0b)
(cherry picked from commit 9072f2c44c23dd78320a286f64482116009002f6)
Signed-off-by: Stefano Radaelli <stefano.r@variscite.com>